---
apiVersion: v1
kind: Namespace
metadata:
  name: astarte
---
apiVersion: v1
kind: Namespace
metadata:
  name: haproxy-kubernetes-ingress
---
apiVersion: v1
kind: Namespace
metadata:
  name: scylla-operator
---
apiVersion: v1
kind: Namespace
metadata:
  name: astarte-operator
