resources:
  - namespaces.yaml
helmCharts:
  - name: cert-manager
    releaseName: cert-manager
    version: "1.20.2"
    includeCRDs: true
    namespace: cert-manager
    repo: https://charts.jetstack.io
    valuesInline:
      crds:
        enabled: true
